### ISSUE TITLE
speed output not as expected

### ISSUE THREAD

**Issue by xxhenglyxx** [processprocess/mouse-speed#2]
I use it with React onMouseMouse event, which it return the event object that I could pass into your mouseSpeed function. The speed sometimes correct and sometimes not. I am implementing a drag selection that marks how many column of time that I have selected. onMouseDown I trigger then onMouseMove event by a boolean flag set to true, onMouseUp simply set the flag to false and do what I need to do there then reset the selection.
The problem that on initial onMouseDown, the mouseSpeed ( event ).y sometimes return very big negative value or big positive value instead of small value from the start, unless we mouse move it very fast.

**Comment by processprocess** [comment]
Hi @xxhenglyxx  - thanks for submitting this.

There was a bug on the first calculation. This has been fixed in the new version. Please be sure to view the readme for set up instructions since the speed values are now accessed differently.

In your React project you will no longer need to create an OnMouseMove event for this. Uou will instead pass a function to mouse-move when you initiate it. I'm happy to take a look at your code if you have any questions!

Thank you for your feedback!
